// @vitest-environment jsdom
import { afterEach,beforeEach,expect,it,vi } from 'vitest'
import { cleanup,fireEvent,render,screen,waitFor,within } from '@testing-library/react'
import { MemoryRouter } from 'react-router-dom'
import App from '../../App'
import type { PullStatus, StabilityPull } from '../../api/stability'
import { AuthProvider } from '../../auth/AuthContext'
import { CapabilityProvider } from '../../auth/CapabilityContext'
import { tokenStorage } from '../../auth/tokenStorage'

const meta={created_at:'2026-01-01T00:00:00Z',updated_at:'2026-01-01T00:00:00Z',version:4}
const study={...meta,id:'study1',organization_id:'o1',business_unit_id:null,division_id:null,department_id:null,study_number:'S-001',study_name:'Active Study',material_id:'m1',stability_protocol_version_id:'v1',start_date:'2026-01-01',status:'ACTIVE',batch_number:null,lot_number:null,notes:null}
const context={protocol_condition:{id:'c1',code:'LONG',name:'Long term'},timepoint:{id:'t1',label:'Month 1',sequence_number:1,is_initial:false},assigned_instrument:{id:'i1',code:'CH-1',name:'Main Chamber',status:'AVAILABLE'}}
const pull=(id:string,status:PullStatus,extra:Partial<StabilityPull>={}):StabilityPull=>({...meta,id,stability_study_id:'study1',stability_study_condition_id:'a1',stability_protocol_timepoint_id:'t1',specification_version_id:'sv1',scheduled_date:'2026-02-03',status,qc_sample_id:null,pulled_at:null,notes:null,qc_sample:null,...context,...extra})
const basePulls=[pull('scheduled','SCHEDULED'),pull('pulled','PULLED',{pulled_at:'2026-02-03T10:30:00Z'}),pull('created','SAMPLE_CREATED',{qc_sample_id:'sample1',qc_sample:{id:'sample1',sample_number:'QC-100',status:'REGISTERED'}}),pull('cancelled','CANCELLED')]
const user=(permissions:string[])=>({id:'me',username:'u',email:'u@test',display_name:'User',force_password_change:false,permissions})
const json=(x:unknown,status=200)=>new Response(JSON.stringify(x),{status,headers:{'Content-Type':'application/json'}})
function mock(permissions:string[],options:{pulls?:ReturnType<typeof pull>[];mutationStatus?:number}={}){let rows=options.pulls??basePulls;return vi.spyOn(globalThis,'fetch').mockImplementation(async(input,init)=>{const url=String(input);if(url.endsWith('/auth/me'))return json(user(permissions));if(url.endsWith('/modules/enabled'))return json(['STABILITY']);if(url==='/api/stability-studies')return json([study]);if(url==='/api/stability-protocols')return json([{...meta,id:'p1',organization_id:'o1',protocol_code:'STAB',protocol_name:'Protocol',description:null,is_active:true}]);if(url.endsWith('/stability-protocols/p1/versions'))return json([{...meta,id:'v1',stability_protocol_id:'p1',version_number:1,version_label:null,status:'APPROVED',effective_from:null,effective_to:null,description:null}]);if(url.endsWith('/stability-protocols/p1/versions/v1/conditions'))return json([{...meta,id:'c1',stability_protocol_version_id:'v1',sequence_number:1,condition_code:'LONG',condition_name:'Long term',temperature_value:null,temperature_unit:null,temperature_tolerance:null,humidity_value:null,humidity_unit:null,humidity_tolerance:null,description:null}]);if(url.endsWith('/stability-studies/study1'))return json(study);if(url.includes('/study1/conditions'))return json([{...meta,id:'a1',stability_study_id:'study1',stability_protocol_condition_id:'c1',instrument_id:'i1',assigned_at:null,ended_at:null,notes:null}]);if(url.includes('/study1/pulls/')&&init?.method==='POST'){if(options.mutationStatus)return json({detail:'Stale Pull version.'},options.mutationStatus);if(url.endsWith('/mark-pulled'))rows=rows.map(x=>x.id==='scheduled'?{...x,status:'PULLED',pulled_at:'2026-02-03T11:30:00.000Z',version:5}:x);if(url.endsWith('/create-sample'))rows=rows.map(x=>x.id==='pulled'?{...x,status:'SAMPLE_CREATED',qc_sample_id:'sample2',qc_sample:{id:'sample2',sample_number:'QC-CALLER',status:'REGISTERED'},version:5}:x);if(url.endsWith('/cancel'))rows=rows.map(x=>x.id==='scheduled'?{...x,status:'CANCELLED',version:5}:x);return json(rows[0])}if(url.includes('/study1/pulls'))return json(rows);return json([])})}
const mount=()=>render(<AuthProvider><CapabilityProvider><MemoryRouter initialEntries={['/app/stability/studies']}><App/></MemoryRouter></CapabilityProvider></AuthProvider>)
async function openStudy(){fireEvent.click(await screen.findByRole('button',{name:'View'}));await screen.findByRole('heading',{name:'Pull Schedule'})}
beforeEach(()=>{localStorage.clear();tokenStorage.set('token');vi.restoreAllMocks()});afterEach(cleanup)

it('gates loading and renders the quiet unavailable message',async()=>{const fetchMock=mock(['stability_study.view']);mount();await openStudy();expect(screen.getByText('Pull Schedule is unavailable with your current permissions.')).toBeTruthy();expect(fetchMock.mock.calls.some(([url])=>String(url).includes('/study1/pulls'))).toBe(false)})

it('loads contextual labels, all statuses, date values, and QC handoff',async()=>{mock(['stability_study.view','stability_pull.view','sample.view']);mount();await openStudy();expect((await screen.findAllByText('LONG — Long term')).length).toBeGreaterThan(0);expect(screen.getAllByText('Month 1').length).toBeGreaterThan(0);expect(screen.getAllByText('CH-1 — Main Chamber — AVAILABLE').length).toBeGreaterThan(0);for(const label of ['Scheduled','Pulled','Sample Created','Cancelled'])expect(screen.getAllByText(label).length).toBeGreaterThan(0);expect(screen.getAllByText('2026-02-03').length).toBeGreaterThan(0);expect(screen.getByText('QC-100')).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'Open QC Samples'}));expect(await screen.findByRole('heading',{name:'Samples'})).toBeTruthy()})

it('sends backend filters and pagination and resets offset on filter change',async()=>{const many=Array.from({length:25},(_,i)=>pull(`p${i}`,'SCHEDULED'));const fetchMock=mock(['stability_study.view','stability_pull.view','stability_protocol.view'],{pulls:many});mount();await openStudy();await screen.findByText('Pulls 1–25');fireEvent.click(screen.getByRole('button',{name:'Next'}));await waitFor(()=>expect(fetchMock.mock.calls.some(([url])=>String(url).includes('offset=25'))).toBe(true));fireEvent.change(screen.getByLabelText('Pull Status'),{target:{value:'PULLED'}});fireEvent.change(screen.getByLabelText('Pull Study Condition'),{target:{value:'a1'}});fireEvent.change(screen.getByLabelText('Pull Scheduled From'),{target:{value:'2026-01-01'}});fireEvent.change(screen.getByLabelText('Pull Scheduled To'),{target:{value:'2026-12-31'}});await waitFor(()=>expect(fetchMock.mock.calls.some(([url])=>{const value=String(url);return value.includes('status=PULLED')&&value.includes('study_condition_id=a1')&&value.includes('scheduled_from=2026-01-01')&&value.includes('scheduled_to=2026-12-31')&&value.includes('limit=25')&&value.includes('offset=0')})).toBe(true))})

it('applies the action matrix and sends exact mark, cancel, and sample bodies',async()=>{const fetchMock=mock(['stability_study.view','stability_pull.view','stability_pull.execute','sample.create']);vi.spyOn(window,'confirm').mockReturnValue(true);mount();await openStudy();await screen.findByRole('button',{name:'Mark Pulled'});expect(screen.getByRole('button',{name:'Cancel Pull'})).toBeTruthy();expect(screen.getByRole('button',{name:'Create QC Sample'})).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'Mark Pulled'}));expect((screen.getByLabelText('Pulled At') as HTMLInputElement).value).toBe('');fireEvent.change(screen.getByLabelText('Pulled At'),{target:{value:'2026-02-03T16:30'}});fireEvent.submit(screen.getByRole('heading',{name:'Mark Month 1 Pulled'}).closest('form')!);await waitFor(()=>expect(fetchMock.mock.calls.some(([url,init])=>String(url).endsWith('/scheduled/mark-pulled')&&JSON.parse(String(init?.body)).version===4&&JSON.parse(String(init?.body)).notes===null&&String(JSON.parse(String(init?.body)).pulled_at).endsWith('Z'))).toBe(true));const originalPulledRow=screen.getByText('3/2/2026, 4:30:00 pm').closest('tr')!;fireEvent.click(within(originalPulledRow).getByRole('button',{name:'Create QC Sample'}));expect(screen.getByLabelText('Sample Number')).toBeTruthy();expect(screen.queryByLabelText(/Material|Priority|Due/)).toBeNull();fireEvent.change(screen.getByLabelText('Sample Number'),{target:{value:'  qc-caller  '}});fireEvent.submit(screen.getByRole('heading',{name:'Create QC Sample'}).closest('form')!);await waitFor(()=>expect(fetchMock.mock.calls.some(([url,init])=>String(url).endsWith('/pulled/create-sample')&&JSON.parse(String(init?.body)).sample_number==='qc-caller'&&JSON.parse(String(init?.body)).version===4)).toBe(true))})

it('hides mutations without complete permissions and reconciles 409 explicitly',async()=>{const fetchMock=mock(['stability_study.view','stability_pull.view','stability_pull.execute'],{mutationStatus:409});vi.spyOn(window,'confirm').mockReturnValue(true);mount();await openStudy();expect(await screen.findByRole('button',{name:'Mark Pulled'})).toBeTruthy();expect(screen.queryByRole('button',{name:'Create QC Sample'})).toBeNull();fireEvent.click(screen.getByRole('button',{name:'Cancel Pull'}));expect(await screen.findByRole('alert')).toBeTruthy();const refresh=screen.getByRole('button',{name:'Refresh Pull Schedule'});fireEvent.click(refresh);await waitFor(()=>expect(fetchMock.mock.calls.filter(([url])=>String(url).includes('/study1/pulls')&&!String(url).includes('/study1/pulls/')).length).toBeGreaterThan(1))})
