// @vitest-environment jsdom
import { afterEach,beforeEach,expect,it,vi } from 'vitest'
import { cleanup,fireEvent,render,screen,waitFor } from '@testing-library/react'
import { MemoryRouter } from 'react-router-dom'
import App from '../../App'
import { AuthProvider } from '../../auth/AuthContext'
import { CapabilityProvider } from '../../auth/CapabilityContext'
import { tokenStorage } from '../../auth/tokenStorage'

const meta={created_at:'2026-01-01T00:00:00Z',updated_at:'2026-01-01T00:00:00Z',version:4}
const protocol={...meta,id:'p1',organization_id:'o1',protocol_code:'STAB',protocol_name:'Stability',description:null,is_active:true}
const version={...meta,id:'v1',stability_protocol_id:'p1',version_number:1,version_label:null,status:'APPROVED',effective_from:null,effective_to:null,description:null}
const study={...meta,id:'study1',organization_id:'o1',business_unit_id:'bu1',division_id:'d1',department_id:'dep1',study_number:'S-001',study_name:'Study',material_id:'m1',stability_protocol_version_id:'v1',start_date:'2026-01-01',status:'DRAFT',batch_number:'B1',lot_number:'L1',notes:null}
const assignment={...meta,id:'a1',stability_study_id:'study1',stability_protocol_condition_id:'c1',instrument_id:'i1',assigned_at:null,ended_at:null,notes:null}
const condition={...meta,id:'c1',stability_protocol_version_id:'v1',sequence_number:1,condition_code:'LONG',condition_name:'Long term',temperature_value:null,temperature_unit:null,temperature_tolerance:null,humidity_value:null,humidity_unit:null,humidity_tolerance:null,description:null}
const material={...meta,id:'m1',organization_id:'o1',code:'MAT',name:'Material',description:null,is_active:true,material_type:'OTHER',default_unit_of_measure:null}
const instrument={...meta,id:'i1',organization_id:'o1',business_unit_id:null,division_id:null,department_id:null,instrument_type_id:'it',manufacturer_id:null,location_id:null,responsible_user_id:null,instrument_code:'CH-1',instrument_name:'Chamber',model_number:null,serial_number:null,description:null,status:'AVAILABLE',criticality:null,calibration_required:false,maintenance_required:false,qualification_required:false,is_active:true}
const user=(permissions:string[])=>({id:'me',username:'u',email:'u@test',display_name:'User',force_password_change:false,permissions})
const json=(x:unknown,status=200)=>new Response(JSON.stringify(x),{status,headers:{'Content-Type':'application/json'}})
function mock(permissions:string[]){return vi.spyOn(globalThis,'fetch').mockImplementation(async(input,init)=>{const u=String(input);if(u.endsWith('/auth/me'))return json(user(permissions));if(u.endsWith('/modules/enabled'))return json(['STABILITY']);if(u.includes('/materials'))return json([material]);if(u.includes('/business-units'))return json([{id:'bu1',business_unit_code:'BU',business_unit_name:'Business',is_active:true},{id:'bu2',business_unit_code:'BU2',business_unit_name:'Other',is_active:true}]);if(u.includes('/divisions'))return json([{id:'d1',business_unit_id:'bu1',division_code:'D',division_name:'Division',is_active:true}]);if(u.includes('/departments'))return json([{id:'dep1',division_id:'d1',department_code:'DEP',department_name:'Department',is_active:true}]);if(u.includes('/instruments'))return json([instrument]);if(u.includes('/versions/v1/conditions'))return json([condition]);if(u.includes('/stability-protocols/p1/versions'))return json([version]);if(u==='/api/stability-protocols')return json([protocol]);if(u.includes('/study1/conditions'))return json([assignment]);if(u.endsWith('/stability-studies/study1'))return json(study);if(u==='/api/stability-studies')return json([study]);if(init?.method)return json(study);return json([])})}
const mount=(path='/app/stability/studies')=>render(<AuthProvider><CapabilityProvider><MemoryRouter initialEntries={[path]}><App/></MemoryRouter></CapabilityProvider></AuthProvider>)
beforeEach(()=>{localStorage.clear();tokenStorage.set('token');vi.restoreAllMocks()});afterEach(cleanup)

it('gates Study navigation and renders view-only data without mutation controls',async()=>{mock(['stability_study.view']);mount('/app');expect(await screen.findByRole('link',{name:'Stability Studies'})).toBeTruthy();cleanup();mock(['stability_study.view']);mount();expect(await screen.findByText('S-001')).toBeTruthy();expect(screen.queryByRole('button',{name:/Create Study|Edit|Activate|Cancel/})).toBeNull()})

it('uses dependent hierarchy, exact approved Protocol Version, and current lifecycle version',async()=>{const fetchMock=mock(['stability_study.view','stability_study.create','stability_study.update','stability_study.cancel','material.view','stability_protocol.view','business_unit.view','division.view','department.view']);vi.spyOn(window,'confirm').mockReturnValue(true);mount();fireEvent.click(await screen.findByRole('button',{name:'Create Study'}));expect((await screen.findByRole('option',{name:'STAB — Version 1 — APPROVED'}) as HTMLOptionElement).value).toBe('v1');fireEvent.change(screen.getByLabelText('Business Unit'),{target:{value:'bu1'}});fireEvent.change(screen.getByLabelText('Division'),{target:{value:'d1'}});fireEvent.change(screen.getByLabelText('Department'),{target:{value:'dep1'}});fireEvent.change(screen.getByLabelText('Business Unit'),{target:{value:'bu2'}});expect((screen.getByLabelText('Division') as HTMLSelectElement).value).toBe('');expect((screen.getByLabelText('Department') as HTMLSelectElement).value).toBe('');fireEvent.click(screen.getAllByRole('button',{name:'Cancel'})[0]);fireEvent.click(screen.getByRole('button',{name:'Activate'}));await waitFor(()=>expect(fetchMock.mock.calls.some(([u])=>String(u).endsWith('/study1/activate'))).toBe(true));const call=fetchMock.mock.calls.find(([u])=>String(u).endsWith('/study1/activate'));expect(JSON.parse(String(call?.[1]?.body))).toEqual({version:4})})

it('shows human-readable chamber assignments and draft lifecycle controls',async()=>{mock(['stability_study.view','stability_study.update','instrument.view','stability_protocol.view']);mount();fireEvent.click(await screen.findByRole('button',{name:'View'}));expect(await screen.findByText('LONG — Long term')).toBeTruthy();expect(screen.getByText('CH-1 — Chamber — AVAILABLE')).toBeTruthy();expect(screen.getByRole('button',{name:'Assign Condition'})).toBeTruthy();expect(screen.getByRole('button',{name:'Delete'})).toBeTruthy()})

it('renders hierarchy lookup labels instead of raw UUIDs',async()=>{mock(['stability_study.view','business_unit.view','division.view','department.view']);mount();expect(await screen.findByText('BU — Business / D — Division / DEP — Department')).toBeTruthy();expect(screen.queryByText('bu1 / d1 / dep1')).toBeNull()})
