"""add sample test assignments

Revision ID: 0af626218d6c
Revises: f19a0c6e8b05
Create Date: 2026-08-31 00:00:59.087920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0af626218d6c'
down_revision: Union[str, Sequence[str], None] = 'f19a0c6e8b05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qc_sample_test_assignments',
    sa.Column('sample_test_id', sa.UUID(), nullable=False),
    sa.Column('assigned_user_id', sa.UUID(), nullable=False),
    sa.Column('assigned_by_user_id', sa.UUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('unassigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unassigned_by_user_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sample_test_id'], ['sample_tests.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['unassigned_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_qc_sample_test_assignments_active', 'qc_sample_test_assignments', ['is_active'], unique=False)
    op.create_index('ix_qc_sample_test_assignments_assigned_user', 'qc_sample_test_assignments', ['assigned_user_id'], unique=False)
    op.create_index(op.f('ix_qc_sample_test_assignments_assigned_user_id'), 'qc_sample_test_assignments', ['assigned_user_id'], unique=False)
    op.create_index('ix_qc_sample_test_assignments_sample_test_active', 'qc_sample_test_assignments', ['sample_test_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_qc_sample_test_assignments_sample_test_id'), 'qc_sample_test_assignments', ['sample_test_id'], unique=False)
    op.execute('CREATE UNIQUE INDEX uq_qc_sample_test_assignments_active ON qc_sample_test_assignments (sample_test_id) WHERE is_active = true')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP INDEX IF EXISTS uq_qc_sample_test_assignments_active')
    op.drop_index(op.f('ix_qc_sample_test_assignments_sample_test_id'), table_name='qc_sample_test_assignments')
    op.drop_index('ix_qc_sample_test_assignments_sample_test_active', table_name='qc_sample_test_assignments')
    op.drop_index(op.f('ix_qc_sample_test_assignments_assigned_user_id'), table_name='qc_sample_test_assignments')
    op.drop_index('ix_qc_sample_test_assignments_assigned_user', table_name='qc_sample_test_assignments')
    op.drop_index('ix_qc_sample_test_assignments_active', table_name='qc_sample_test_assignments')
    op.drop_table('qc_sample_test_assignments')
    # ### end Alembic commands ###
