"""Enhance user model

Revision ID: 3dac3d42e6bd
Revises: ac6a218ad3d9
Create Date: 2026-08-07 13:35:11.441130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dac3d42e6bd'
down_revision: Union[str, Sequence[str], None] = 'ac6a218ad3d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('department_id', sa.UUID(), nullable=False))
    op.add_column('users', sa.Column('designation_id', sa.UUID(), nullable=False))
    op.add_column('users', sa.Column('display_name', sa.String(length=200), nullable=False))
    op.add_column('users', sa.Column('mobile', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('account_status', sa.String(length=20), nullable=False))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('password_changed_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('force_password_change', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('timezone', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('language', sa.String(length=20), nullable=False))
    op.create_foreign_key(None, 'users', 'designations', ['designation_id'], ['id'])
    op.create_foreign_key(None, 'users', 'departments', ['department_id'], ['id'])
    op.drop_column('users', 'is_locked')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_locked', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'language')
    op.drop_column('users', 'timezone')
    op.drop_column('users', 'force_password_change')
    op.drop_column('users', 'password_changed_at')
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'account_status')
    op.drop_column('users', 'mobile')
    op.drop_column('users', 'display_name')
    op.drop_column('users', 'designation_id')
    op.drop_column('users', 'department_id')
    # ### end Alembic commands ###
