"""Add designations

Revision ID: ac6a218ad3d9
Revises: c85063c38db1
Create Date: 2026-08-07 12:26:00.667997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac6a218ad3d9'
down_revision: Union[str, Sequence[str], None] = 'c85063c38db1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('designations',
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('designation_code', sa.String(length=20), nullable=False),
    sa.Column('designation_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('can_approve_workflows', sa.Boolean(), nullable=False),
    sa.Column('can_manage_assets', sa.Boolean(), nullable=False),
    sa.Column('can_schedule_calibration', sa.Boolean(), nullable=False),
    sa.Column('can_execute_calibration', sa.Boolean(), nullable=False),
    sa.Column('can_close_service', sa.Boolean(), nullable=False),
    sa.Column('can_manage_documents', sa.Boolean(), nullable=False),
    sa.Column('can_review_results', sa.Boolean(), nullable=False),
    sa.Column('can_release_results', sa.Boolean(), nullable=False),
    sa.Column('can_manage_users', sa.Boolean(), nullable=False),
    sa.Column('can_view_reports', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_designations_designation_code'), 'designations', ['designation_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_designations_designation_code'), table_name='designations')
    op.drop_table('designations')
    # ### end Alembic commands ###
