"""Add business units

Revision ID: fa7ffb86d593
Revises: 6a24b91c2a3c
Create Date: 2026-08-06 02:05:58.979842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa7ffb86d593'
down_revision: Union[str, Sequence[str], None] = '6a24b91c2a3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_units',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('business_unit_code', sa.String(length=20), nullable=False),
    sa.Column('business_unit_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_units_business_unit_code'), 'business_units', ['business_unit_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_business_units_business_unit_code'), table_name='business_units')
    op.drop_table('business_units')
    # ### end Alembic commands ###
