// @vitest-environment jsdom
import { afterEach, beforeEach, expect, it, vi } from 'vitest'
import { cleanup, fireEvent, render, screen } from '@testing-library/react'
import { MemoryRouter } from 'react-router-dom'
import App from '../../App'
import { AuthProvider } from '../../auth/AuthContext'
import { CapabilityProvider } from '../../auth/CapabilityContext'
import { tokenStorage } from '../../auth/tokenStorage'

const user=(permissions:string[])=>({id:'me',username:'u',email:'u@test',display_name:'User',force_password_change:false,permissions})
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json'}})
const dates={created_at:'2026-01-01T00:00:00Z',updated_at:'2026-01-01T00:00:00Z',version:4}
const test={...dates,id:'test-1',organization_id:'org',test_code:'ASSAY',test_name:'Assay',description:null,test_category:'Chemical',default_unit:'%',is_active:true}
const method={...dates,id:'method-1',organization_id:'org',method_code:'HPLC',method_name:'HPLC Assay',description:null,is_active:true}
const methodVersion={...dates,id:'mv-1',method_id:'method-1',version_number:2,version_label:'Current',status:'APPROVED',effective_from:null,effective_to:null,source_reference:'SOP-2',description:null}
const draftMethodVersion={...methodVersion,id:'mv-draft',version_number:3,status:'DRAFT',source_reference:'SOP-DRAFT',version:1}
const parameter={...dates,id:'param-1',method_version_id:'mv-draft',parameter_code:'FLOW',parameter_name:'Flow',value_type:'NUMBER',unit:'mL/min',default_value:'1.0',sequence_number:1,is_required:true,description:null}
const material={...dates,id:'mat-1',organization_id:'org',code:'FG-1',name:'Finished Good',description:null,is_active:true,material_type:'FINISHED_PRODUCT',default_unit_of_measure:'kg'}
const specification={...dates,id:'spec-1',organization_id:'org',material_id:'mat-1',specification_code:'REL',specification_name:'Release',description:null,is_active:true}
const specVersion={...dates,id:'sv-1',specification_id:'spec-1',version_number:1,version_label:'Draft',status:'DRAFT',effective_from:null,effective_to:null,description:null}
const specTest={...dates,id:'st-1',specification_version_id:'sv-1',test_id:'test-1',method_version_id:'mv-1',sequence_number:1,is_required:true,display_name:'Assay',instructions:null}
const limit={...dates,id:'limit-1',specification_test_id:'st-1',parameter_name:'Result',criterion_type:'BETWEEN',lower_limit:'90',upper_limit:'110',target_value:null,text_value:null,boolean_value:null,unit:'%',sequence_number:1,description:null}

function mockApi(permissions:string[]){return vi.spyOn(globalThis,'fetch').mockImplementation(async(input,init)=>{const url=String(input);if(url.endsWith('/auth/me'))return json(user(permissions));if(url.endsWith('/modules/enabled'))return json([]);if(url.includes('/materials'))return json([material]);if(url==='/api/tests'||url.startsWith('/api/tests?'))return json([test]);if(url.includes('/methods/method-1/versions/mv-draft/parameters'))return json([parameter]);if(url.includes('/methods/method-1/versions'))return json([draftMethodVersion,methodVersion]);if(url==='/api/methods'||url.startsWith('/api/methods?'))return json([method]);if(url.includes('/specifications/spec-1/versions/sv-1/tests/st-1/limits'))return json([limit]);if(url.includes('/specifications/spec-1/versions/sv-1/tests'))return json([specTest]);if(url.includes('/specifications/spec-1/versions'))return json([specVersion]);if(url==='/api/specifications'||url.startsWith('/api/specifications?'))return json([specification]);if(init?.method)return json({detail:'Record changed. Refresh and try again.'},409);return json([])})}
function renderPath(path:string){return render(<AuthProvider><CapabilityProvider><MemoryRouter initialEntries={[path]}><App/></MemoryRouter></CapabilityProvider></AuthProvider>)}
beforeEach(()=>{localStorage.clear();tokenStorage.set('token');vi.restoreAllMocks()});afterEach(cleanup)

it('shows exact Laboratory Masters navigation and guards direct routes',async()=>{mockApi(['test.view']);const first=renderPath('/app');expect(await screen.findByRole('link',{name:'Laboratory Masters'})).toBeTruthy();first.unmount();mockApi(['user.view']);renderPath('/app/laboratory-masters/tests');expect(await screen.findByRole('heading',{name:'Not authorized'})).toBeTruthy()})

it('renders Tests and keeps view-only users read-only',async()=>{mockApi(['test.view']);renderPath('/app/laboratory-masters/tests');expect(await screen.findByText('ASSAY')).toBeTruthy();expect(screen.getByText('Chemical')).toBeTruthy();expect(screen.queryByRole('button',{name:'Create test'})).toBeNull();expect(screen.queryByRole('button',{name:'Edit'})).toBeNull()})

it('sends Test expected version and presents stale refresh',async()=>{const fetchMock=mockApi(['test.view','test.update']);renderPath('/app/laboratory-masters/tests');fireEvent.click(await screen.findByRole('button',{name:'Edit'}));fireEvent.change(screen.getByLabelText('Name'),{target:{value:'Changed'}});fireEvent.click(screen.getByRole('button',{name:'Save'}));expect((await screen.findByRole('alert')).textContent).toContain('Record changed');expect(screen.getByRole('button',{name:'Refresh current data'})).toBeTruthy();const call=fetchMock.mock.calls.find(([u,i])=>String(u).includes('/tests/test-1')&&i?.method==='PUT');expect(JSON.parse(call?.[1]?.body as string).version).toBe(4)})

it('shows Method versions, DRAFT controls, historical read-only state, and parameters',async()=>{mockApi(['method.view','method.create','method.update']);renderPath('/app/laboratory-masters/methods');fireEvent.click(await screen.findByRole('button',{name:'Versions'}));expect(await screen.findByText('SOP-2')).toBeTruthy();expect(screen.getByRole('button',{name:'Approve'})).toBeTruthy();const parameterButtons=screen.getAllByRole('button',{name:'Parameters'});fireEvent.click(parameterButtons[0]);expect(await screen.findByText('FLOW')).toBeTruthy();expect(screen.getByRole('button',{name:'Add parameter'})).toBeTruthy();fireEvent.click(parameterButtons[1]);expect(await screen.findByText(/Historical version/)).toBeTruthy();expect(screen.queryByRole('button',{name:'Add parameter'})).toBeNull()})

it('uses readable Specification lookups, exact MethodVersion, and adaptive limit fields',async()=>{mockApi(['specification.view','specification.create','specification.update','material.view','test.view','method.view']);renderPath('/app/laboratory-masters/specifications');expect((await screen.findAllByText('FG-1 — Finished Good')).length).toBeGreaterThan(0);fireEvent.click(screen.getByRole('button',{name:'Create specification'}));expect(screen.getAllByRole('option',{name:'FG-1 — Finished Good'}).length).toBeGreaterThan(0);expect(screen.queryByLabelText(/UUID/)).toBeNull();fireEvent.click(screen.getByRole('button',{name:'Versions'}));fireEvent.click(await screen.findByRole('button',{name:'Tests'}));expect(await screen.findByText('HPLC — Version 2 — APPROVED')).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'Limits'}));expect(await screen.findByText('90–110 %')).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'Add limit'}));fireEvent.change(screen.getByLabelText('Criterion'),{target:{value:'TEXT_MATCH'}});expect(screen.getByLabelText('Text Value')).toBeTruthy();expect(screen.queryByLabelText('Lower Limit')).toBeNull();fireEvent.change(screen.getByLabelText('Criterion'),{target:{value:'BOOLEAN'}});expect(screen.getByLabelText('Boolean Value')).toBeTruthy()})

it('presents backend approval-readiness failures without claiming success',async()=>{const fetchMock=mockApi(['specification.view','specification.update']);fetchMock.mockImplementation(async(input,init)=>{const url=String(input);if(url.endsWith('/auth/me'))return json(user(['specification.view','specification.update']));if(url.endsWith('/modules/enabled'))return json([]);if(url.includes('/versions/sv-1/approve')&&init?.method==='POST')return json({detail:'An approval-ready Specification Version requires at least one Test.'},400);if(url.includes('/specifications/spec-1/versions'))return json([specVersion]);if(url==='/api/specifications'||url.startsWith('/api/specifications?'))return json([specification]);return json([])});vi.spyOn(window,'confirm').mockReturnValue(true);renderPath('/app/laboratory-masters/specifications');fireEvent.click(await screen.findByRole('button',{name:'Versions'}));fireEvent.click(await screen.findByRole('button',{name:'Approve'}));expect((await screen.findByRole('alert')).textContent).toContain('requires at least one Test')})
