import { useCallback, useEffect, useState, type FormEvent } from 'react'
import { ApiError } from '../../api/client'
import { testsApi, type Input, type Test } from '../../api/qc'
import { useAuthorization } from '../../auth/useAuthorization'
import { AdminHeader, ConfirmButton, EmptyState, ErrorState, LoadingState, errorMessage } from '../../components/admin/AdminPrimitives'

function TestForm({record,onSave,onCancel}:{record?:Test;onSave:(data:Input)=>Promise<void>;onCancel:()=>void}){ const [v,setV]=useState({test_code:record?.test_code??'',test_name:record?.test_name??'',test_category:record?.test_category??'',default_unit:record?.default_unit??'',description:record?.description??''}); const [saving,setSaving]=useState(false); async function submit(e:FormEvent){e.preventDefault();setSaving(true);try{await onSave({...v,test_category:v.test_category||null,default_unit:v.default_unit||null,description:v.description||null})}finally{setSaving(false)}} return <form className="admin-form form-grid" onSubmit={submit}><h2>{record?'Edit test':'Create test'}</h2><label>Code<input value={v.test_code} onChange={e=>setV({...v,test_code:e.target.value})} required/></label><label>Name<input value={v.test_name} onChange={e=>setV({...v,test_name:e.target.value})} required/></label><label>Category<input value={v.test_category} onChange={e=>setV({...v,test_category:e.target.value})}/></label><label>Default Unit<input value={v.default_unit} onChange={e=>setV({...v,default_unit:e.target.value})}/></label><label className="full-width">Description<textarea value={v.description} onChange={e=>setV({...v,description:e.target.value})}/></label><div className="form-actions full-width"><button disabled={saving}>Save</button><button type="button" className="text-button" onClick={onCancel}>Cancel</button></div></form> }

export function TestsPage(){ const {hasPermission}=useAuthorization(); const [rows,setRows]=useState<Test[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[conflict,setConflict]=useState(false),[editing,setEditing]=useState<Test|null>(null),[creating,setCreating]=useState(false),[search,setSearch]=useState(''),[active,setActive]=useState('all'),[category,setCategory]=useState(''); const load=useCallback(async()=>{setLoading(true);try{setRows(await testsApi.list({search:search||undefined,is_active:active==='all'?undefined:active==='active',category:category||undefined}));setError(null);setConflict(false)}catch(e){setError(errorMessage(e))}finally{setLoading(false)}},[search,active,category]); useEffect(()=>{queueMicrotask(()=>void load())},[load]); async function mutate(op:()=>Promise<unknown>){try{await op();setEditing(null);setCreating(false);await load()}catch(e){setConflict(e instanceof ApiError&&e.status===409);setError(errorMessage(e))}}
return <section className="admin-page"><AdminHeader title="Tests" description="Manage what the laboratory measures." actions={hasPermission('test.create')&&<button className="small-button" onClick={()=>setCreating(true)}>Create test</button>}/>{error&&<><ErrorState message={error}/>{conflict&&<button className="small-button secondary refresh-button" onClick={()=>void load()}>Refresh current data</button>}</>}{creating&&<TestForm onCancel={()=>setCreating(false)} onSave={d=>mutate(()=>testsApi.create(d))}/>} {editing&&<TestForm record={editing} onCancel={()=>setEditing(null)} onSave={d=>mutate(()=>testsApi.update(editing.id,editing.version,d))}/>}<div className="inline-form"><label>Search<input aria-label="Search tests" value={search} onChange={e=>setSearch(e.target.value)}/></label><label>Status<select aria-label="Test status filter" value={active} onChange={e=>setActive(e.target.value)}><option value="all">All</option><option value="active">Active</option><option value="inactive">Inactive</option></select></label><label>Category<input aria-label="Category filter" value={category} onChange={e=>setCategory(e.target.value)}/></label></div>{loading?<LoadingState/>:rows.length===0?<EmptyState>No tests found.</EmptyState>:<div className="table-wrap"><table><thead><tr><th>Code</th><th>Name</th><th>Category</th><th>Default unit</th><th>Active</th><th>Version</th><th>Actions</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.test_code}</td><td>{r.test_name}</td><td>{r.test_category??'—'}</td><td>{r.default_unit??'—'}</td><td><span className={`status-pill ${r.is_active?'active':'inactive'}`}>{r.is_active?'Active':'Inactive'}</span></td><td>{r.version}</td><td className="table-actions">{hasPermission('test.update')&&<><button className="small-button secondary" onClick={()=>setEditing(r)}>Edit</button><ConfirmButton className="small-button secondary" prompt={`${r.is_active?'Deactivate':'Activate'} ${r.test_name}?`} onConfirm={()=>void mutate(()=>testsApi.setActive(r.id,r.version,!r.is_active))}>{r.is_active?'Deactivate':'Activate'}</ConfirmButton></>}{hasPermission('test.delete')&&<ConfirmButton prompt={`Delete ${r.test_name}?`} onConfirm={()=>void mutate(()=>testsApi.remove(r.id,r.version))}>Delete</ConfirmButton>}</td></tr>)}</tbody></table></div>}</section> }
