// @vitest-environment jsdom
import { afterEach,beforeEach,expect,it,vi } from 'vitest'
import { cleanup,fireEvent,render,screen,waitFor } from '@testing-library/react'
import { MemoryRouter } from 'react-router-dom'
import App from '../../App'
import { AuthProvider } from '../../auth/AuthContext'
import { tokenStorage } from '../../auth/tokenStorage'

const user={id:'user-1',organization_id:'org-1',business_unit_id:'bu-1',division_id:'div-1',department_id:'dep-1',designation_id:'des-1',employee_code:'E1',first_name:'Current',last_name:'User',display_name:'Current User',email:'current@test',mobile:null,username:'current',account_status:'ACTIVE',timezone:'UTC',language:'en',failed_login_attempts:0,last_login:null,created_at:'',updated_at:''}
const lookups={organizations:[{id:'org-1',organization_code:'ORG1',organization_name:'Primary Lab'},{id:'org-2',organization_code:'ORG2',organization_name:'Hidden Lab'}],business_units:[{id:'bu-1',organization_id:'org-1',business_unit_code:'BU1',business_unit_name:'Quality'},{id:'bu-2',organization_id:'org-2',business_unit_code:'BU2',business_unit_name:'Hidden'}],divisions:[{id:'div-1',business_unit_id:'bu-1',division_code:'DIV1',division_name:'Laboratory'}],departments:[{id:'dep-1',division_id:'div-1',department_code:'DEP1',department_name:'QC'}],designations:[{id:'des-1',department_id:'dep-1',designation_code:'CHEM',designation_name:'Chemist'}]}
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json'}})
const me={id:'me',username:'admin',email:'a@test',display_name:'Admin',force_password_change:false,permissions:['user.view','user.create','user.update']}
function renderPage(){return render(<AuthProvider><MemoryRouter initialEntries={['/app/administration/users']}><App/></MemoryRouter></AuthProvider>)}
function mockApi(){return vi.spyOn(globalThis,'fetch').mockImplementation(async(input,init)=>{const url=String(input);if(url.endsWith('/auth/me'))return json(me);if(url.includes('/hierarchy-lookups/'))return json(lookups);if(url==='/api/users/'&&init?.method==='POST')return json(user);if(url.endsWith('/users/user-1')&&init?.method==='PUT')return json(user);if(url==='/api/users/')return json([user]);return json({})})}
beforeEach(()=>{localStorage.clear();tokenStorage.set('token');vi.restoreAllMocks()});afterEach(cleanup)

it('creates users through required human-readable cascading hierarchy selectors and submits IDs',async()=>{
 const fetchMock=mockApi();renderPage();fireEvent.click(await screen.findByRole('button',{name:'Create user'}));
 const organization=await screen.findByLabelText('Organization');expect(screen.queryByLabelText('Organization ID')).toBeNull();expect(screen.getByRole('option',{name:'ORG1 — Primary Lab'})).toBeTruthy();
 fireEvent.change(organization,{target:{value:'org-1'}});expect(screen.getByRole('option',{name:'BU1 — Quality'})).toBeTruthy();expect(screen.queryByRole('option',{name:'BU2 — Hidden'})).toBeNull();
 fireEvent.change(screen.getByLabelText('Business Unit'),{target:{value:'bu-1'}});expect(screen.getByRole('option',{name:'DIV1 — Laboratory'})).toBeTruthy();fireEvent.change(screen.getByLabelText('Division'),{target:{value:'div-1'}});expect(screen.getByRole('option',{name:'DEP1 — QC'})).toBeTruthy();fireEvent.change(screen.getByLabelText('Department'),{target:{value:'dep-1'}});expect(screen.getByRole('option',{name:'CHEM — Chemist'})).toBeTruthy();fireEvent.change(screen.getByLabelText('Designation'),{target:{value:'des-1'}});
 fireEvent.change(organization,{target:{value:'org-2'}});expect((screen.getByLabelText('Business Unit') as HTMLSelectElement).value).toBe('');expect((screen.getByLabelText('Division') as HTMLSelectElement).value).toBe('');expect((screen.getByLabelText('Department') as HTMLSelectElement).value).toBe('');expect((screen.getByLabelText('Designation') as HTMLSelectElement).value).toBe('');
 fireEvent.change(organization,{target:{value:'org-1'}});fireEvent.change(screen.getByLabelText('Business Unit'),{target:{value:'bu-1'}});fireEvent.change(screen.getByLabelText('Division'),{target:{value:'div-1'}});fireEvent.change(screen.getByLabelText('Department'),{target:{value:'dep-1'}});fireEvent.change(screen.getByLabelText('Designation'),{target:{value:'des-1'}});
 for(const [label,value] of [['Employee code','E20'],['First name','Sprint20'],['Last name','A'],['Display name','Sprint20 User A'],['Email','a20@test'],['Username','sprint20a'],['Temporary password','ValidPass123!']])fireEvent.change(screen.getByLabelText(label),{target:{value}});fireEvent.click(screen.getByRole('button',{name:'Create'}));
 await waitFor(()=>expect(fetchMock.mock.calls.some(([u,i])=>String(u)==='/api/users/'&&i?.method==='POST')).toBe(true));const call=fetchMock.mock.calls.find(([u,i])=>String(u)==='/api/users/'&&i?.method==='POST');expect(JSON.parse(String(call?.[1]?.body))).toMatchObject({organization_id:'org-1',business_unit_id:'bu-1',division_id:'div-1',department_id:'dep-1',designation_id:'des-1'});expect((organization as HTMLSelectElement).required).toBe(true)
})

it('resolves Edit hierarchy labels, cascades descendants, and submits authorized replacement IDs',async()=>{
 const fetchMock=mockApi();renderPage();fireEvent.click(await screen.findByRole('button',{name:'View/Edit'}));expect((await screen.findByLabelText('Organization') as HTMLSelectElement).value).toBe('org-1');expect(screen.getByRole('option',{name:'ORG1 — Primary Lab'})).toBeTruthy();expect((screen.getByLabelText('Designation') as HTMLSelectElement).value).toBe('des-1');
 fireEvent.change(screen.getByLabelText('Business Unit'),{target:{value:''}});expect((screen.getByLabelText('Division') as HTMLSelectElement).value).toBe('');expect((screen.getByLabelText('Department') as HTMLSelectElement).value).toBe('');expect((screen.getByLabelText('Designation') as HTMLSelectElement).value).toBe('');
 fireEvent.change(screen.getByLabelText('Business Unit'),{target:{value:'bu-1'}});fireEvent.change(screen.getByLabelText('Division'),{target:{value:'div-1'}});fireEvent.change(screen.getByLabelText('Department'),{target:{value:'dep-1'}});fireEvent.change(screen.getByLabelText('Designation'),{target:{value:'des-1'}});fireEvent.click(screen.getByRole('button',{name:'Save changes'}));await waitFor(()=>expect(fetchMock.mock.calls.some(([u,i])=>String(u).endsWith('/users/user-1')&&i?.method==='PUT')).toBe(true));const call=fetchMock.mock.calls.find(([u,i])=>String(u).endsWith('/users/user-1')&&i?.method==='PUT');expect(JSON.parse(String(call?.[1]?.body))).toMatchObject({organization_id:'org-1',business_unit_id:'bu-1',division_id:'div-1',department_id:'dep-1',designation_id:'des-1'})
})

it('shows backend lifecycle transitions for PENDING and ACTIVE users and refreshes after activation',async()=>{
 vi.spyOn(window,'confirm').mockReturnValue(true);const pending={...user,id:'pending',display_name:'Pending User',username:'pending',email:'pending@test',account_status:'PENDING'},active={...user,id:'active',display_name:'Active User',username:'active',email:'active@test',account_status:'ACTIVE'};let rows=[pending,active];const fetchMock=vi.spyOn(globalThis,'fetch').mockImplementation(async(input,init)=>{const url=String(input);if(url.endsWith('/auth/me'))return json(me);if(url.includes('/hierarchy-lookups/'))return json(lookups);if(url==='/api/users/')return json(rows);if(url.endsWith('/users/pending/activate')&&init?.method==='PUT'){rows=[{...pending,account_status:'ACTIVE'},active];return json(rows[0])}return json({})});renderPage();await screen.findByText('Pending User');const pendingRow=screen.getByText('Pending User').closest('tr')!,activeRow=screen.getByText('Active User').closest('tr')!;expect(pendingRow.querySelector('button')?.textContent).toBe('View/Edit');expect(Array.from(pendingRow.querySelectorAll('button')).map(x=>x.textContent)).toContain('Activate');expect(Array.from(pendingRow.querySelectorAll('button')).map(x=>x.textContent)).not.toContain('Deactivate');expect(Array.from(activeRow.querySelectorAll('button')).map(x=>x.textContent)).toContain('Deactivate');fireEvent.click(Array.from(pendingRow.querySelectorAll('button')).find(x=>x.textContent==='Activate')!);await waitFor(()=>expect(fetchMock.mock.calls.some(([u,i])=>String(u).endsWith('/users/pending/activate')&&i?.method==='PUT')).toBe(true));await waitFor(()=>expect(screen.getByText('Pending User').closest('tr')?.textContent).toContain('ACTIVE'))
})
